[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm run start"
# force rebuild Sat Jul 11 22:14:13     2026
